### ISSUE TITLE
ACTION_CREATE_DOCUMENT kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by walaoehh** [itzmeanjan/intent#22]
I am trying to create a file using ACTION_CREATE_DOCUMENT. The intent launch the file manager but once after I save the file, my flutter apps dies to this exception.

```
Intent()
      ..setAction(Action.ACTION_CREATE_DOCUMENT)
      ..setType("application/pdf")
      ..setData(Uri(path: path))
      ..addCategory(intent_category.Category.CATEGORY_OPENABLE)
      ..putExtra(Extra.EXTRA_TITLE, "path.pdf")
      ..startActivityForResult()
          .catchError((e) => print(e))
          .then((value) => print(value));
```

```
E/AndroidRuntime(11603): Caused by: kotlin.KotlinNullPointerException
E/AndroidRuntime(11603): 	at io.github.itzmeanjan.intent.IntentPlugin.uriToFilePath(IntentPlugin.kt:252)
E/AndroidRuntime(11603): 	at io.github.itzmeanjan.intent.IntentPlugin.access$uriToFilePath(IntentPlugin.kt:20)
E/AndroidRuntime(11603): 	at io.github.itzmeanjan.intent.IntentPlugin$onMethodCall$1.onActivityResult(IntentPlugin.kt:58)
E/AndroidRuntime(11603): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(11603): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(11603): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime(11603): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:699)
E/AndroidRuntime(11603): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:510)
E/AndroidRuntime(11603): 	at android.app.Activity.dispatchActivityResult(Activity.java:8393)
E/AndroidRuntime(11603): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5442
```

**Comment by itzmeanjan** [comment]
Hey @walaoehh , thanks for reporting !!!

I'm digging in :)

**Comment by itzmeanjan** [comment]
Hello @walaoehh , change your usage to 

```dart
Intent()
      ..setAction(Action.ACTION_CREATE_DOCUMENT)
      ..setType("application/pdf")
      ..setData(Uri(path: path))
      ..addCategory(intent_category.Category.CATEGORY_OPENABLE)
      ..putExtra(Extra.EXTRA_TITLE, "path.pdf")
      ..startActivity().catchError((e) => print(e));
```
Let me know whether it does work or not ?

**Comment by walaoehh** [comment]
Yes, it will work but I need to use startActivityForResult() to get the path of the created file.

**Comment by itzmeanjan** [comment]
Well, that's not supported yet :(

I'll take a note :)

**Comment by etmyhome** [comment]
any update? 
i need get the path returned from  startActivityForResult
