### ISSUE TITLE
RuntimeException picking contact

### ISSUE THREAD

**Issue by pharshdev** [itzmeanjan/intent#32]
```
Launching lib/main.dart on Note 4 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Error: ADB exited with exit code 1
Performing Streamed Install

Connecting to VM Service at ws://127.0.0.1:61073/sX4EAUGJxbU=/ws
D/AndroidRuntime(23277): Shutting down VM
E/AndroidRuntime(23277): FATAL EXCEPTION: main
E/AndroidRuntime(23277): Process: com.example.xxx, PID: 23277
E/AndroidRuntime(23277): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=999, result=-1, data=Intent { dat=content://com.android.contacts/data/869 flg=0x1 }} to activity {com.example.xxx/com.example.xxx.MainActivity}: java.lang.IllegalArgumentException: Invalid column _data
E/AndroidRuntime(23277): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
E/AndroidRuntime(23277): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440)
E/AndroidRuntime(23277): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(23277): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(23277): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(23277): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
E/AndroidRuntime(23277): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23277): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23277): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/AndroidRuntime(23277): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23277): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(23277): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(23277): Caused by: java.lang.IllegalArgumentException: Invalid column _data
E/AndroidRuntime(23277): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
E/AndroidRuntime(23277): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime(23277): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
E/AndroidRuntime(23277): 	at android.content.ContentResolver.query(ContentResolver.java:803)
E/AndroidRuntime(23277): 	at android.content.ContentResolver.query(ContentResolver.java:753)
E/AndroidRuntime(23277): 	at android.content.ContentResolver.query(ContentResolver.java:711)
E/AndroidRuntime(23277): 	at io.github.itzmeanjan.intent.IntentPlugin.uriToFilePath(IntentPlugin.kt:241)
E/AndroidRuntime(23277): 	at io.github.itzmeanjan.intent.IntentPlugin.access$uriToFilePath(IntentPlugin.kt:20)
E/AndroidRuntime(23277): 	at io.github.itzmeanjan.intent.IntentPlugin$onMethodCall$1.onActivityResult(IntentPlugin.kt:58)
E/AndroidRuntime(23277): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(23277): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(23277): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime(23277): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:582)
E/AndroidRuntime(23277): 	at android.app.Activity.dispatchActivityResult(Activity.java:7462)
E/AndroidRuntime(23277): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
E/AndroidRuntime(23277): 	... 11 more
I/Process (23277): Sending signal. PID: 23277 SIG: 9
Lost connection to device.
Exited (sigterm)

```

**Comment by itzmeanjan** [comment]
I don't see any code sample, which you used for invoking this intent.

**Comment by pharshdev** [comment]
Copy pasted the snippet from Readme.md
```
 Intent()
                ..setAction(Action.ACTION_PICK)
                ..setData(Uri.parse('content://contacts'))
                ..setType("vnd.android.cursor.dir/phone_v2")
                ..startActivityForResult().then((data) => print(data),
                onError: (e) => print(e));
```
